# Parameters for DSDM actuator controller node


robot_type:     'BoeingArm'       # 
robot_config:   'dual-plane'      #
a0_zero:         0.05             # zero value of actuator 0
a1_zero:         4.2            # zero value of actuator 1
a2_zero:         -3.14            # zero value of actuator 2

