# Parameters for ctc controller

# Control mode type
controller:     'RollSLD'         #   RminCTC or RfixCTC or RminSLD or RfixSLD or RollCTC or RollSLD
fixed_mode:      0                #

# Robot type
n_gears:         2                # number of possible gear selection
goal:           [-3.3,-2.0,0,0]   # target state

# General 
hysteresis:      true          # true or false hysteresis mode
min_delay:       0.5           #

# CTC only
w0:              8.0
zeta:            0.7

# Sliding only
lam:             3.0
nab:             3.0
D:               1.0

# Roll Only
horizon:         0.2           #
sim_dt:          0.1           #
domain_check:    true

